update bin/supply

diff --git a/bin/finalize b/bin/finalize
--- a/bin/finalize
+++ b/bin/finalize
@@ -9,48 +9,55 @@ DEPS_DIR=$3
 DEPS_IDX=$4
 PROFILE_DIR=${5:-}
 
-WSO2_MI_HOME="wso2mi-1.1.0-SNAPSHOT"
-JDK_VERSION="jdk-8u161-linux-x64"
+WSO2_MI_VERSION="wso2mi-1.1.0-SNAPSHOT"
+WSO2_MI_ZIP="${WSO2_MI_VERSION}.zip"
+JDK_VERSION="jdk1.8.0_161"
+MVN_VERSION="apache-maven-3.3.9"
 
 export BUILDPACK_DIR=$(dirname $(dirname $0))
-export JAVA_HOME=${DEPS_DIR}/${DEPS_IDX}/${JDK_VERSION}
+export JAVA_HOME="${DEPS_DIR}/${DEPS_IDX}/${JDK_VERSION}"
+export MVN_HOME=${DEPS_DIR}/${DEPS_IDX}/${MVN_VERSION}
+export PATH="$PATH:${JAVA_HOME}/bin:${MVN_HOME}/bin"
+echo $PATH
 output_dir=$(mktemp -d -t finalizeXXX)
-
 
 echo "-----> Running finalize"
 
-source "${APP_DIR}/wso2-mi"
+#source "${APP_DIR}/wso2-mi"
+CURRENT_DIR=$(pwd)
+cd ${APP_DIR}
+
+echo "-----> Building the WSO2 CompositeApp"
+mvn clean install -X
+
+cd ${CURRENT_DIR}CURRENT_DIR;
 
 TMP_DIR=$(mktemp -d -t finalizeXXX)
 
-echo "-----> Unzipping ${BUILDPACK_DIR}/resources/${WSO2_MI_HOME}.zip"
-if ! unzip -q -d ${TMP_DIR} ${BUILDPACK_DIR}/resources/${WSO2_MI_HOME}.zip;
+echo "-----> Unzipping ${BUILDPACK_DIR}/resources/${WSO2_MI_ZIP}"
+if ! unzip -q -d ${TMP_DIR} ${BUILDPACK_DIR}/resources/${WSO2_MI_ZIP};
  then
-    echo "unable to unzip ${WSO2_MI_HOME}.zip"
+    echo "unable to unzip ${WSO2_MI_ZIP}"
     exit 1
 fi
 
+echo "-----> Starting WSO2 Micro Integrator ..."
+${TMP_DIR}/${WSO2_MI_VERSION}/bin/micro-integrator.sh
 
-echo "-----> Building Micro Integrator"
-if ! ${TMP_DIR}/${WSO2_MI_HOME}/bin/micro-integrator build cf;
-then
-    echo "unable to create the project: cf"
-    exit 1
-fi
+#echo "-----> Unzipping Micro Integrator distribution"
+#if ! unzip -q -d ${APP_DIR} $(pwd)/cf/target/mi-cf.zip;
+# then
+#   echo "unable to unzip the project zip: mi-cf.zip"
+#   exit 1
+#fi
 
-echo "-----> Unzipping Micro Integrator distribution"
-if ! unzip -q -d ${APP_DIR} $(pwd)/cf/target/mi-cf.zip;
- then
-   echo "unable to unzip the project zip: mi-cf.zip"
-   exit 1
-fi
 
-echo "-----> Setting up permission"
-if ! chmod +x ${APP_DIR}/mi-cf/bin/micro-integrator.sh;
- then
-    echo  "couldn't configure permission for ${APP_DIR}/mi-cf/bin/"
-    exit 1
-fi
+#echo "-----> Setting up permission"
+#if ! chmod +x ${APP_DIR}/mi-cf/bin/micro-integrator.sh;
+# then
+#    echo  "couldn't configure permission for ${APP_DIR}/mi-cf/bin/"
+#    exit 1
+#fi
 
 echo "-----> Create the directory ${APP_DIR}/.profile.d"
 # to add envs create a bash script with required env in .profile.d
diff --git a/bin/supply b/bin/supply
--- a/bin/supply
+++ b/bin/supply
@@ -22,18 +22,12 @@ if ! mkdir -p ${DEPS_DIR}/${DEPS_IDX};
 fi
 
 # Java
-JDK_VERSION="jdk-8u161-linux-x64"
-JDK_TAR="${JDK_VERSION}.tar.gz"
+JDK_VERSION="jdk1.8.0_161"
 
-echo "-----> Creating ${DEPS_DIR}/${DEPS_IDX}/${JDK_VERSION}"
-if ! mkdir -p ${DEPS_DIR}/${DEPS_IDX}/${JDK_VERSION};
- then
-    echo  "couldn't create the directory ${DEPS_DIR}/${DEPS_IDX}/${JDK_VERSION}"
-    exit 1
-fi
+JDK_TAR="jdk-8u161-linux-x64.tar.gz"
 
-echo "-----> Unpacking JDK: ${JDK_TAR} to  ${DEPS_DIR}/${DEPS_IDX}/${JDK_VERSION}"
-if ! tar -xf ${RESOURCES_DIR}/${JDK_TAR} -C ${DEPS_DIR}/${DEPS_IDX}/${JDK_VERSION};
+echo "-----> Unpacking JDK: ${JDK_TAR} to  ${DEPS_DIR}/${DEPS_IDX}"
+if ! tar -xf ${RESOURCES_DIR}/${JDK_TAR} -C ${DEPS_DIR}/${DEPS_IDX};
  then
   echo  "couldn't extract the JDK to ${DEPS_DIR}/${DEPS_IDX}"
   exit 1
@@ -44,7 +38,7 @@ cat << EOF > ${DEPS_DIR}/${DEPS_IDX}/config.yml
 ---
 config:
   JDKVersion: jdk-8u161-linux-x64
-name: wso2-mi
+name: wso2_micro_integrator_buildpack
 version: 1.0.0
 EOF
 
@@ -52,17 +46,11 @@ EOF
 MVN_VERSION="apache-maven-3.3.9"
 MVN_TAR="${MVN_VERSION}-bin.tar.gz"
 
-echo "-----> Creating ${DEPS_DIR}/${DEPS_IDX}/${MVN_VERSION}"
-if ! mkdir -p ${DEPS_DIR}/${DEPS_IDX}/${MVN_VERSION};
- then
-    echo  "couldn't create the directory ${DEPS_DIR}/${DEPS_IDX}/${MVN_VERSION}"
-    exit 1
-fi
 
-echo "-----> Unpacking Maven: ${MVN_TAR} to  ${DEPS_DIR}/${DEPS_IDX}/${MVN_VERSION}"
-if ! tar -xf ${RESOURCES_DIR}/${MVN_TAR} -C ${DEPS_DIR}/${DEPS_IDX}/${MVN_VERSION};
+echo "-----> Unpacking Maven: ${MVN_TAR} to  ${DEPS_DIR}/${DEPS_IDX}"
+if ! tar -xf ${RESOURCES_DIR}/${MVN_TAR} -C ${DEPS_DIR}/${DEPS_IDX};
  then
-    echo  "couldn't extract Maven to ${DEPS_DIR}/${DEPS_IDX}/${MVN_VERSION}"
+    echo  "couldn't extract Maven to ${DEPS_DIR}/${DEPS_IDX}"
     exit 1
 fi
 
